/**
 * Re-export of the Supabase-generated `Database` type.
 *
 * The actual type is generated by running `pnpm --filter @mch/db gen:types`
 * while `supabase start` is up. Until that has been run at least once, a stub
 * is committed so downstream packages stay type-checkable.
 */
export type { Database } from './types.generated.js';
