/**
 * STUB: regenerated by `pnpm --filter @mch/db gen:types`.
 *
 * Do not hand-edit. Replaced wholesale by the Supabase CLI output.
 */
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
